### ISSUE TITLE
Very slow on macOS

### ISSUE THREAD

**Issue by nulaft** [efrantar/twophase#13]
I have a machine running both Ubuntu and macOS natively. rob-twophase runs as fast as expected on Ubuntu, while it is very slow on macOS:

```
$ ./twophase -t 1 -l 22 -m 10000  # compiled without extra solve mode defines
solve UDFUURRLDBFLURRDRUUFLLFRFDBRBRLDBUDLRBBFLBBUDDFFDBUFLL
```
Ubuntu: 0.2 ms
macOS: 430 ms, or 1200 ms, or even > 10000 ms.
The time it takes is different every time I restart twophase, but it is pretty consistent for a session. I have no other programs running.

I used the provided makefile for compilation and the compiler provided by macOS:
```
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Any ideas?

**Comment by nulaft** [comment]
If I remove -lpthread from LDLIBS in the makefile, it still compiles successfully on macOS and it is much faster. However, it does not compile without -lpthread on Ubuntu.

**Comment by nulaft** [comment]
Apparently -lpthread is outdated and -pthread should be used instead (PR #14 ). I couldn't notice a performance difference between -lpthread and -pthread on Ubuntu, but on macOS -pthread (or nothing) it is at least an order of magnitude faster than -lpthread. This brings me from hundredths of milliseconds to tens of milliseconds for computing one length 22 HTM solution.

**Comment by nulaft** [comment]
On Ubuntu, I always get this solution, even if I restart twophase:
```
0.189ms B2 L2 U2 R2 F2 R2 F' R2 F2 U2 B' R2 F2 D' L' R' U' B2 L' U' F' U (22)
```

However, on macOS I get different solutions every time I restart twophase, and they take wildly different times to be found:
```
0199.799ms F D2 B' L2 F2 D2 L2 B2 D F2 L' D' R' F2 L D F R' U' F' L' F' (22)
0009.292ms U L U F U D' R2 B D F2 U' R U' R' L2 F2 R' B2 L U2 R L' (22)
1242.050ms F2 U B2 U2 L2 D' U2 L' U' B D' L' F' U2 F' D2 R2 D' U' L' F U' (22)
0049.267ms R2 U2 F2 R' D2 R' U2 L B F' R2 F2 U' R' D2 L' R2 D' F L F' R2 (22)
...
```

**Comment by efrantar** [comment]
Unfortunately, I have absolutely no experience with MacOS, I only develop on Linux ...

With `-t 1` the program should be 100% deterministic, getting different solutions sounds a bit like some kind of access to undefined memory (that changes on every run), perhaps caused by optimization (`-O3` compiler flag). I would recommend to count the number of `phase1()` and `phase2()` calls. If they correlate with the solving time, then that's probably the issue.

I can't help you directly with debugging as I do not have access to a MacOS system. Some things to check that may help with narrowing down the problem:

- Are the numbers printed when generating the pruning tables exactly the same (for Linux and Mac)? Are the `.tbl`-files exactly the same?
- Dump all parameters at the beginning of every `phase1()` and `phase2()` call to see where they start to differ for Linux/MacOS.

Maybe I have some more ideas with that further information.

PS: You appear to be very interested in my solver, I am curious what you are planning to use it for? :)

**Comment by nulaft** [comment]
I have installed gcc on macOS (the system compiler is clang which is remapped to the g++ command). I've also removed the -O3 optimization flag. The behavior is the same.
The table files are identical on macOS and Ubuntu. I haven't checked if the numbers that are printed are the same but they should be because the files are identical, right?

I'll try your other suggestions and report my findings.
Maybe valgrind can also help with this.

I am developing a cube solving robot with 4 grippers. I am not planning to go for any records, sub 6s or so should suffice as a goal :) The software should be rather optimized, so the robot can look like it knows what it is doing while moving. This solver is a great start for that. I'm currently working on translating the cube moves into optimal robot moves. My algorithm works, but it is still too slow, around 40ms for one translation. And I would like to go through dozens of solutions to find the one that the robot can solve the fastest. AXQT is a good metric to find promising solutions, but since the robot can only turn 4 faces it needs to perform cube rotations, and there are faster and slower ones depending on how the grippers block each other. Maybe I can hack in a F4 mode that at least adds the minimum number of required cube rotations to the solution length?

**Comment by nulaft** [comment]
I've found two arrays from which uninitialized values were read from. PR #16 fixes this. Now the output is deterministic and just as fast as on Ubuntu.

**Comment by efrantar** [comment]
Great that you managed to fix it!

Regarding your robot, it so happens that I have also been working on a quad-arm (e.g. a CubeStormer-like) robot since the beginning of this March (although just as my other robots I am working with Lego and I am trying to push as far as possible in terms of speed) ^^

In fact, I have already spent a lot of time developing a new kind of solving algorithm fully optimized for the robot's mechanics, i.e. one that directly takes all kinds of cube rotations and advanced regrips into account while searching for a solution. This was insanely tricky to get working properly and I had to come up with various major new techniques to address all the challenges such a solving algorithm brings with it. Once my robot is complete, which I hope it will be soonish (maybe a few months at most), I will of course publish this solver as well.

Hence, if you just want a very good solving algorithm but don't necessarily care about developing (parts of) it yourself and have other stuff to take care of in the mean-time (e.g. mechanics, color recognition, etc.), you might want to wait a bit before investing a lot of effort trying to "hack" some stuff into rob-twophase. Otherwise, using rob-twophase to find maybe 10 solutions in the appropriate metric and then select the best of them for the robot's mechanics is certainly a sensible approach that will probably already give very decent results. 

Either way, I just wanted to be transparent about this and good luck (6 seconds is already a very ambitious goal for an unmodified cube solver) for your robot, I am looking forward to seeing it in action. :)
