### ISSUE TITLE
Made with -DQT -DAX Fails to run on raspberry pi

### ISSUE THREAD

**Issue by toughmanshawn** [efrantar/twophase#19]
I get 
`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
`
When running ./twophase after making with the flags -DQT -DAX 
On Raspberry Pi
Without any flags works though. 

Update: It works on raspberry pi 4 with 4gb of ram but not pi 3b

**Comment by toughmanshawn** [comment]
It works on raspberry pi 4 with 4gb of ram but not pi 3b

**Comment by efrantar** [comment]
Hi! In axial mode `-DAX`, this solver requires twice the amount of RAM (i.e. 1.2 GB instead of 676 MB) as the number of possible moves increases (i.e. there are now also moves that turn two faces at the same time) and the extended phase 1 table thus has to store more information for optimal performance. In general, this solver is designed for the best possible solving performance and not necessarily for resource efficiency. If you want the best possible performance, you may also want to consider running the solver on a PC/Laptop (with a decent processor) that communicates with the Raspberry (e.g. via USB).

**Comment by toughmanshawn** [comment]
Yeah It does require more ram. I was able to get it to run by expanding the virtual ram size but it was way to slow. Decided that if I am going to use it I am going to need a better computer. Thanks!
