### ISSUE TITLE
batch solving rubik's cubes

### ISSUE THREAD

**Issue by physxP** [efrantar/twophase#20]
Hi!

In the README file it is mentioned that 

> cube20src clearly remains the best choice for batch-solving a very large number of cubes

So, if batch solving is our priority is cube20src actually better than rob-twophase?

**Comment by efrantar** [comment]
Yes, for batch solving it is probably optimal to use one thread per cube, whereas one of the core features of this solver is to use multiple threads to solve a single cube (as you only solve one cube at a time with a robot). Assuming that you are only interested in standard metrics that are also supported by `cube20src` (rather than in the robot metrics supported only by `rob-twophase`), then I would use it for batch solving. However, unless you want to solve a really large number of cubes (e.g. like for proving an upper bound), the practical difference will likely be quite small.

**Comment by physxP** [comment]
Thank you so much for the detailed response
